 // spells and abilities
// [universal][dependent]
//  spells = "unit":[dark/black][white][dependent/hidden arts][dependent/hidden abilities]
// unit:  [growth][perosnal ability, [unit_specific arts],[unit specific ablities][lostitem][likeditem]
// [unit_specific arts] = [["art name","skill req"]]
//


// class: [growth][[class abilites],class arts][class masteries][skill requirements]
// [class masteries]



// character specific spells, abilities and arts
// should include dark magic range/dark tomefaire vs black magic versions

var spells = {

    "Byleth"     : [["Fire (D)", "Thunder (D+)", "Bolganone (C)", "Ragnarok (A)"                       ],["Heal (D)", "Nosferatu (D+)", "Recover (C)", "Aura (A)"                 ]],
    "Edelgard"   : [["Fire (D)", "Bolganone (C)", "Luna Λ (B)", "Hades Ω (A)"                          ],["Heal (D)", "Nosferatu (D+)", "Recover (C)", "Seraphim (B)"             ]],
    "Hubert"     : [["Miasma Δ (D)", "Mire Β (D+)", "Banshee Θ (C)", "Death Γ (B)", "Dark Spikes Τ (A)"],["Heal (D)", "Nosferatu (D+)", "Recover (C)"                             ]],
    "Dorothea"   : [["Thunder (D)", "Thoron (C)", "Sagittae (B)", "Meteor (A)", "Agnea’s Arrow (A+)"   ],["Heal (D)", "Nosferatu (D+)", "Physic (C)"                              ]],
    "Ferdinand"  : [["Thunder (D)", "Fire (D+)", "Thoron (C)", "Bolganone (B)"                         ],["Heal (D)", "Nosferatu (D+)", "Ward (C)", "Restore (B)"                 ]],
    "Bernadetta" : [["Blizzard (D)", "Thunder (D+)", "Thoron (C)", "Fimbulvetr (A)"                    ],["Heal (D)", "Nosferatu (D+)", "Physic (C)", "Rescue (A)"                   ]],
    "Caspar"     : [["Fire (D)", "Bolganone (C)"                                                       ],["Heal (D)", "Nosferatu (D+)", "Recover (C)"                             ]],
    "Petra"      : [["Wind (D)", "Sagittae (C)"                                                        ],["Heal (D)", "Nosferatu (D+)", "Restore (C)"                             ]],
    "Linhardt"   : [["Wind (D)", "Fire (D+)", "Cutting Gale (C)", "Bolganone (B)", "Excalibur (A)"     ],["Heal (D)", "Nosferatu (D+)", "Physic (C)", "Restore (B)", "Warp (A)"   ]],
    "Dimitri"    : [["Thunder (D)", "Thoron (C)"                                                       ],["Heal (D)", "Nosferatu (D+)", "Recover (C)", "Aura (A)"                 ]],
    "Dedude"      : [["Fire (D)", "Bolganone (C)", "Ragnarok (A)"                                      ],["Heal (D)", "Nosferatu (D+)", "Recover (C)"                             ]],
    "Felix"      : [["Thunder (D)", "Thoron (C)"                                                       ],["Heal (D)", "Noferatu (D+)", "Recover (C)", "Restore (B)"               ]],
    "Mercedes"   : [["Fire (D)", "Thunder (D+)", "Bolganone (C)", "Ragnarok (A)"                       ],["Heal (D)", "Nosferatu (D+)", "Physic (C)", "Restore (B)", "Fortify (A)"]],
    "Ashe"       : [["Wind (D)", "Cutting Gale (C)"                                                    ],["Heal (D)", "Nosferatu (D+)", "Physic (C)"                              ]],
    "Annette"    : [["Wind (D)", "Cutting Gale (C)", "Sagittae (B)", "Excalibur (A)"                   ],["Heal (D)", "Nosferatu (D+)", "Recover (C)", "Abraxas (A)"              ]],
    "Sylvain"    : [["Fire (D)", "Bolganone (C)", "Sagittae (B)", "Ragnarok (A)"                       ],["Heal (D)", "Nosferatu (D+)", "Physic (C)", "Seraphim (B)"              ]],
    "Ingrid"     : [["Blizzard (D)", "Thoron (C)", "Fimbulvetr (A)"                                    ],["Heal (D)", "Nosferatu (D+)", "Physic (C)", "Seraphim (B)"              ]],
    "Claude"     : [["Wind (D)", "Sagittae (C)", "Cutting Gale (B)", "Excalibur (A)"                   ],["Heal (D)", "Nosferatu (D+)", "Recover (C)", "Silence (A)"              ]],
    "Lorenz"     : [["Fire (D)", "Sagittae (C)", "Ragnarok (B)", "Agnea’s Arrow (A)"                   ],["Heal (D)", "Nosferatu (D+)", "Recover (C)", "Ward (B)"                 ]],
    "Hilda"      : [["Thunder (D)", "Thoron (C)", "Bolting (A)"                                        ],["Heal (D)", "Nosferatu (D+)", "Recover (C)"                             ]],
    "Raphael"    : [["Fire (D)", "Bolganone (C)"                                                       ],["Heal (D)", "Nosferatu (D+)", "Recover (C)"                             ]],
    "Lysithea"   : [["Miasma Δ (D)", "Swarm Ζ (D+)", "Luna Λ (C)", "Dark Spikes Τ (B)", "Hades Ω (A)"  ],["Heal (D)", "Nosferatu (D+)", "Seraphim (C)", "Warp (B)", "Abraxas (A)" ]],
    "Ignatz"     : [["Blizzard (D)", "Cutting Gale (C)", "Fimbulvetr (A)"                              ],["Heal (D)", "Nosferatu (D+)", "Physic (C)", "Ward (B)"                  ]],
    "Marianne"   : [["Blizzard (D)", "Thoron (C)", "Cutting Gale (B)", "Fimbulvetr (A)"                ],["Heal (D)", "Nosferatu (D+)", "Physic (C)", "Silence (B)", "Aura (A)"   ]],
    "Leonie"     : [["Fire (D)", "Bolganone (C)", "Ragnarok (A)"                                       ],["Heal (D)", "Nosferatu (D+)", "Physic (C)", "Restore (B)"               ]],
    "Manuela"    : [["Thunder (D)", "Bolganone (C)", "Bolting (A)"                                     ],["Heal (D)", "Nosferatu (D+)", "Ward (C)", "Silence (B)", "Warp (A)"     ]],
    "Hanneman"   : [["Wind (D)", "Sagittae (C)", "Thoron (B)", "Ragnarok (A)", "Meteor (A+)"           ],["Heal (D)", "Nosferatu (D+)", "Recover (C)", "Ward (B)"                 ]],
    "Seteth"     : [["Wind (D)", "Cutting Gale (C)", "Bolganone (B)", "Excalibur (A)"                  ],["Heal (D)", "Nosferatu (D+)", "Recover (C)", ""                         ]],
    "Flayn"      : [["Wind (D)", "Fire (D+)", "Cutting Gale (C)", "Excalibur (A)"                      ],["Heal (D)", "Nosferatu (D+)", "Restore (C)", "Rescue (B)", "Fortify (A)"]],
    "Cyril"      : [["Wind (D)", "Cutting Gale (C)"                                                    ],["Heal (D)", "Nosferatu (D+)", "Recover (C)"                             ]],
    "Catherine"  : [["Fire (D)", "Bolganone (C)", "Ragnarok (A)"                                       ],["Heal (D)", "Nosferatu (D+)", "Recover (C)"                             ]],
    "Alois"      : [["Fire (D)", "Bolganone (C)"                                                       ],["Heal (D)", "Nosferatu (D+)", "Recover (C)"                             ]],
    "Gilbert"    : [["Thunder (D)", "Thoron (C)"                                                       ],["Heal (D)", "Nosferatu (D+)", "Ward (C)"                                ]],
    "Shamir"     : [["Blizzard (D)", "Wind (D+)", "Sagittae (C)", "Fimbulvetr (A)"                     ],["Heal (D)", "Nosferatu (D+)", "Physic (C)"                              ]]

}

// combat art: [stats][note][universal]
// "Name" : [[Might, Hit, Crit, Range, DurCost], Description (Comments)]
// Sword

var combat_arts = {

    "Sunder"              :  [["4–15",1,3       ], "–"],
    "Wrath Strike"        :  [[5,10,"–",1,3,    ], "–"],
    "Grounder"            :  [[3,20,5,1,4       ], "Effective against Flying foes."],
    "Hexblade"            :  [[7,10,"–",1,3     ], "Deals magic-based damage."],
    "Windsweep"           :  [[3,20,10,1,5      ], "Prevent enemy counter-attack."],
    "Haze Slice"          :  [[2,"–","–",1,5    ], "Avoid +30."],
    "Subdue"              :  [[0,20,"–",1,3     ], "Leaves foe with at least 1 HP."],
    "Bane of Monsters"    :  [[6,"–",10,1,4     ], "Effective against Monster foes."],
    "Finesse Blade"       :  [[2,"–","–",1,4    ], "Avoid +10; Might increases based on user’s Dexterity."],
    "Soulblade"           :  [[2,10,"–",1,4     ], "Deals magic-based damage. Might increases based on user’s Resistance."],
    "Foudroyant Strike"   :  [[6,30,30,1,3      ], "Thunderbrand only; effective against Armoured and Dragon foes."],
    "Beast Fang"          :  [[10,"–",30,1,3    ], "Blutgang only; effective against Cavalry and Dragon foes."],
    "Ruptured Heaven"     :  [[7,10,10,"1~2",3  ], "Sword of the Creator only; Might increases based on user’s Magic, effective against Dragon foes."],
    "Heaven’s Fall"       :  [[10,10,10,"1~2",3 ], "Dark Creator Sword only; Might increases based on user’s Magic"],
    "Assassinate"         :  [[0,15,"–",1,5     ], "Assassin only; Avoid +15, can kill enemies instantly."],
    "Astra"               :  [[0,-10,"–",1,9    ], "Swordmaster only; triggers 5 consecutive hits at 30% Might."],
    "Sublime Heaven"      :  [[10,10,20,"1~2",3 ], "Sublime Creator Sword only; Might increases based on user’s Magic, effective against Dragon foes."],
    "Sword Dance"         :  [[1,"–","–",1,2    ], "Avoid +20, Might increases based on user’s Charm."],
    "Tempest Lance"       :  [[8,10,"–" ,1,5    ], "–"],
    "Shatter Slash"       :  [[4,10,"–" ,1,3    ], "After combat, inflicts Def -5 on foe for 1 turn."],
    "Knightkneeler"       :  [[5,15,"–" ,1,4    ], "Effective against Cavalry foes."],
    "Hit and Run"         :  [[4,10,"–" ,1,4    ], "Avoid +20; after combat, user moves 1 space backwards."],
    "Monster Piercer"     :  [[7,"–","–", 1,4   ], "Avoid +10; effective against Monster foes."],
    "Lance Jab"           :  [[3, "–",10,1,5    ], "Might increases based on user’s Speed."],
    "Vengeance"           :  [[2,"–",10,1,4     ], "Damage increases in relation to the user’s missing HP."],
    "Glowing Ember"       :  [[2,"–","–", 1,4   ], "Avoid +10; Might increases based on user’s Defence."],
    "Swift Strikes"       :  [[2,"–","–", 1,4   ], "Triggers 2 consecutive hits."],
    "Frozen Lance"        :  [[3,5,"–",1,4      ], "Deals magic-based damage. Might increases based on user’s Dexterity."],
    "Ruined Sky"          :  [[13,10,10,1,3     ], "Lance of Ruin only; Avoid +10, effective against Flying and Dragon foes."],
    "Atrocity"            :  [[15,20,"–",1,3    ], "Areadbhar only; effective against all foes."],
    "Burning Quake"       :  [[8,"–",20,1,3     ], "Lúin only; Avoid +10; Might increases based on user’s Speed, effective against Dragon foes."],
    "Paraselene"          :  [[10,"–","–",1,3   ], "Great Lord only; Avoid +10, after combat, user moves 1 space backwards."],
    "Smash"               :  [[3,20,20,1,5      ], "–"],
    "Spike"               :  [[5,15,10,1,5      ], "–"],
    "Helm Splitter"       :  [[7,"–" ,5,1,5     ], "Effective against Armoured foes."],
    "Monster Breaker"     :  [[9, "–","–" ,1,5  ], "Effective against Monster foes."],
    "Diamond Axe"         :  [[14,-20,"–" ,1,7  ], "–"],
    "Exhaustive Strike"   :  [[3,10,"–" ,1,1    ], "Depletes all of the weapon’s remaining durability and adds 30% of that value to Might."],
    "Armored Strike"      :  [[3,"–" ,10,1,4    ], "Might increases based on user’s Defence."],
    "Wild Abandon"        :  [[10,-30,30,1,5    ], "–"],
    "Focused Strike"      :  [[0,30,"–" ,1,3    ], "–"],
    "Lightning Axe"       :  [[4,"–" ,"–" ,1,3  ], "Deals magic-based damage. Might increases based on user’s Resistance."],
    "Apocalyptic Flame"   :  [[15,20,"–" ,1,3   ], "Freikugel only; inflicts Str -5 on foe for 1 turn, effective against Dragon foes."],
    "Dust"                :  [[20,"–" ,"–" ,1,3 ], "Crusher only; inflicts Def -5 on foe for 1 turn, effective against Dragon foes."],
    "Raging Storm"        :  [[14,10,"–" ,1,3   ], "Aymr only; if attack lands, user can move again, effective against Dragon foes."],
    "Flickering Flower"   :  [[10,10,10,1,3     ], "Emperor only; prevents foe from moving for 1 turn?"],
    "War Master’s Strike" :  [[3,30,"–" ,1,5    ], "War Master only; effective against all foes."],
    "Curved Shot"         :  [[1,30,"–" ,"2~3",3], "–"],
    "Deadeye"             :  [[6,"–","–","3~5",5], "–"],
    "Heavy Draw"          :  [[8,10,"–" ,2,5    ], "–"],
    "Encloser"            :  [[4,15,"–" ,2,3    ], "Prevents foe from moving for 1 turn?"],
    "Ward Arrow"          :  [[4,15,"–" ,2,3    ], "Prevents foe from using magic for 1 turn?"],
    "Point-Blank Volley"  :  [[3,10,"–" ,1,4    ], "Avoid +10; triggers 2 consecutive hits."],
    "Monster Blast"       :  [[5,"–" ,10,2,4    ], "Effective against Monster foes."],
    "Waning Shot"         :  [[4,10,"–" ,"2~3",3], "After combat, inflicts Str -5 on foe for 1 turn."],
    "Break Shot"          :  [[4,5,"–" ,"2~3",3 ], "After combat, inflicts Def -5 on foe for 1 turn."],
    "Schism Shot"         :  [[4,15,"–" ,"2~3",3], "After combat, inflicts Res -5 on foe for 1 turn."],
    "Fallen Star"         :  [[10,30,10,"2~3",3 ], "Failnaught only; avoids all attacks during the next round of combat; effective against Dragon foes."],
    "Hunter’s Volley"     :  [[1,15,10,"2~3",5  ], "Sniper only; triggers 2 consecutive hits."],
    "Wind God"            :  [[5,20,"–" ,"2~5",3], "Barbarossa only."],
    "Draining Blow"       :  [[5,20,"–" ,1,3    ], "Restores HP equal to 50% of the damage inflicted to the enemy."],
    "Mighty Blow"         :  [[10,-5,20,1,3     ], "–"],
    "Bombard"             :  [[3,"–" ,10,1,3    ], "Triggers 2 consecutive hits."],
    "Rushing Blow"        :  [[7,20,"–" ,1,3    ], "Avoid +10; after combat, user moves 1 space in front of the enemy."],
    "Fading Blow"         :  [[6,10,"–" ,1,3    ], "Avoid +30; after combat, user moves 1 space backwards."],
    "Mystic Blow"         :  [[10,10,"–" ,1,3   ], "Deals magic-based damage."],
    "Nimble Combo"        :  [[4,"–" ,"–" ,1,3  ], "Avoid +20; triggers 2 consecutive hits."],
    "One-Two Punch"       :  [[8,20,"–" ,1,4    ], "Triggers a follow-up attack."],
    "Monster Crusher"     :  [[13,10,10,1,4     ], "Effective against Monster foes."],
    "Fierce Iron Fist"    :  [[1,"–" ,10,1,5    ], "Grappler only; triggers 3 consecutive hits."],
    "Healing Focus"       :  [["–","–","–","–","–" ], "Restores 50% of the user’s HP."],
    "Swap"                :  [["–","–","–",1,"–"   ], "User swaps places with the enemy."],
    "Shove"               :  [["–","–","–",1,"–"   ], "User pushes ally forward 1 space."],
    "Reposition"          :  [["–","–","–",1,"–"   ], "User moves ally to the space behind the user."],
    "Draw Back"           :  [["–","–","–",1,"–"   ], "User moves 1 space backwards and ally is moved to where the user was previously."],
    "Smite"               :  [["–","–","–",1,"–"   ], "User pushes ally forward 2 spaces."],
    "Triangle Attack"     :  [[8,30,40,1,3         ], "Can only be triggered when 3 allied Flying units (including the user) are adjacent to the same enemy."],

}

var universal_arts =[
    "Wrath Strike",
    "Grounder",
    "Tempest Lance",
    "Knightkneeler",
    "Smash",
    "Helm Splitter",
    "Curved Shot",
    "Rushing Blow",
    "Fading Blow",
    "Healing Focus",
    "Smite",

]


var allabilities = {
    "Advocate": ["Adjacent male allies deal 3 extra damage during combat.", "Personal: Hilda"],
    "Aegis": ["Chance to reduce bow/magic damage by half. Trigger % = Dex stat.","Class mastered: Paladin"],
    "Air of Intimidation": ["On Hold", "Unused?"],
    "Alert Stance": ["If unit takes no action except Wait, grants Avo +15 for 1 turn.",    "Raise Flying skill level to B"],
    "Alert Stance+": ["If unit takes no action except Wait, grants Avo +30 for 1 turn.",    "Raise Flying skill level to A+"],
    "Anchor": ["Prevents unit from being moved.", ""],
    "Animal Friend": ["Unit recovers up to 20% of max HP at the start of each turn when adjacent to a cavalry or flying ally.",    "Personal: Marianne"],
    "Aptitude": ["Makes each stat 20% more likely to increase on level up.",    "Personal: Cyril"],
    "Armored Blow": ["If unit initiates combat, grants Def +6 during combat",    "Class mastered: Armored Knight"],
    "Armored Effect Null": ["Nullifies any extra effectiveness against armored units.",    "Raise Heavy Armour skill level to S+"],
    "Authority Lv 1": ["Grants Mt +2 with gambits.",    "Raise Authority skill level to E+"],
    "Authority Lv 2": ["Grants Mt +4 with gambits.",    "Raise Authority skill level to D+"],
    "Authority Lv 3": ["Grants Mt +6 with gambits.",    "Raise Authority skill level to C+"],
    "Authority Lv 4": ["Grants Mt +8 with gambits.",    "Raise Authority skill level to B+"],
    "Authority Lv 5": ["Grants Mt +10 with gambits.",    "Raise Authority skill level to A+"],
    "Avo +10": ["Increases Avo by 10.",    "Class: Pegasus Knight, Falcon Knight, Wyvern Lord"],
    "Axe Avo +20": ["Grants Avo +20 when using an axe.", ""],
    "Axe Crit +10": ["Grants Crit +10 when using an axe.",    "Raise Axe skill level to S, Class: Warrior"],
    "Axe Prowess Lv 1": ["Grants Hit +7, Avo +5, and Crit Avo +5 when using an axe.",    "Raise Axe skill level to E+"],
    "Axe Prowess Lv 2": ["Grants Hit +10, Avo +6, and Crit Avo +6 when using an axe.",    "Raise Axe skill level to D+"],
    "Axe Prowess Lv 3": ["Grants Hit +13, Avo +7, and Crit Avo +7 when using an axe.",    "Raise Axe skill level to C+"],
    "Axe Prowess Lv 4": ["Grants Hit +16, Avo +8, and Crit Avo +8 when using an axe.",    "Raise Axe skill level to B+"],
    "Axe Prowess Lv 5": ["Grants Hit +20, Avo +10, and Crit Avo +10 when using an axe.",    "Raise Axe skill level to A+"],
    "Axebreaker": ["Grants Hit/Avo +20 when using a sword against axe users.",    "Raise Sword skill level to B"],
    "Axebreaker+": ["Grants Hit/Avo +30 when using a sword against axe users.",    ""],
    "Axefaire": ["Grants Atk +5 when using an axe.",    "Raise Axe skill level to S+, Class: Armored Lord, Fortress Knight, Wyvern Rider, Warrior, Emperor, Wyvern Lord, Great Knight, War Master"],
    "Battalion Desperation": ["If unit initiates combat when battalion endurance is ≤ 1/3, unit's follow-up attack (if possible) occurs before foe's counterattack.",    "Raise Authority skill level to C for Dorothea, Ferdinand, Ashe, Ingrid, Claude, Lysithea, Ignatz, Leonie, Hanneman, Cyril or Shamir. Raise to A for protagonist, Hubert or Seteth."],
    "Battalion Renewal": ["Unit recovers up to 30% of max HP at the start of each turn while battalion endurance is ≤ 1/3.",    "Raise Authority skill level to C for Linhardt, Mercedes, Annette, Marianne, Manuela or Flayn. Raise to A for Edelgard."],
    "Battalion Vantage": ["When foe initiates combat, unit still attacks first if battalion endurance is ≤ 1/3.",    "Raise Authority skill level to C for protagonist, Edelgard, Felix, Sylvain, Lorenz or Catherine. Raise to A for Dimitri or Ignatz."],
    "Battalion Wrath": ["If foe initiates combat while unit's battalion endurance is ≤ 1/3, grants Crit +50.",    "Raise Authority skill level to C for Hubert, Bernadetta, Caspar, Petra, Dimitri, Dedue, Hilda, Raphael, Seteth, Alois or Gibert. Raise to A for Annette or Claude."],
    "Black Magic Avo +20": ["Grants Avo +20 when using black magic.",    "Budding talent: Sylvain"],
    "Black Magic Crit +10": ["Grants Crit +10 when using black magic.",    "Budding talent: Edelgard and Felix"],
    "Black Magic Range +1": ["Increases black magic range by 1.",    "Raise Reason skill level to S (except for Edelgard, Hubert and Lysithea)"],
    "Black Magic Uses Up+": ["Quadruples the number of uses for black magic.",    ""],
    "Black Magic Uses x2": ["Doubles the number of uses for black magic.",    "Class: Warlock, Gremory"],
    "Black Tomefaire": ["Grants Atk +5 when using black magic.",    "Raise Reason skill level to S+ (except Edelgard, Hubert and Lysithea), Class: Warlock, Mortal Savant, Dark Knight"],
    "Blade Breaker": ["If unit damages foe, foe suffers Str/Def -6 for 1 turn after combat.",    "Personal: Jeralt"],
    "Born Fighter": ["Adjacent foes suffer Avo -10 during combat.",    "Personal: Caspar"],
    "Bow Avo +20": ["Grants Avo +20 when using a bow.", ""],    "Bow Crit +10": ["Grants Crit +10 when using a bow.",
    "Raise Bow skill level to S"],    "Bow Prowess Lv 1": ["Grants Hit +6, Avo +6, and Crit Avo +5 when using a bow.",
    "Raise Bow skill level to E+"],    "Bow Prowess Lv 2": ["Grants Hit +8, Avo +8, and Crit Avo +6 when using a bow.",
    "Raise Bow skill level to D+"],    "Bow Prowess Lv 3": ["Grants Hit +10, Avo +10, and Crit Avo +7 when using a bow.",
    "Raise Bow skill level to C+"],    "Bow Prowess Lv 4": ["Grants Hit +12, Avo +12, and Crit Avo +8 when using a bow.",
    "Raise Bow skill level to B+"],    "Bow Prowess Lv 5": ["Grants Hit +15, Avo +15, and Crit Avo +10 when using a bow.",
    "Raise Bow skill level to A+"],    "Bowbreaker": ["Grants Hit/Avo +20 when using magic against bow users.",
    "Raise Reason skill level to B"],    "Bowfaire": ["Grants Atk +5 when using a bow.",
    "Raise Bow skill level to S+, Class: Wyvern Master, Sniper, Barbarossa, Bow Knight"],
    "Bowrange +1": ["Increases bow range by 1.", "Class: Archer, Sniper"],
    "Bowrange +2": ["Increases bow range by 2.", "Class: Bow Knight"],
    "Brawl Avo +20": ["Grants Avo +20 when brawling.", ""],
    "Brawl Crit +10": ["Grants Crit +10 when brawling.",    "Raise Brawling skill level to S"],
    "Brawling Prowess Lv 1": ["Grants Hit +5, Avo +7, and Crit Avo +5 when brawling.",    "Raise Brawling skill level to E+"],
    "Brawling Prowess Lv 2": ["Grants Hit +6, Avo +10, and Crit Avo +6 when brawling.",    "Raise Brawling skill level to D+"],
    "Brawling Prowess Lv 3": ["Grants Hit +7, Avo +13, and Crit Avo +7 when brawling.",    "Raise Brawling skill level to C+"],
    "Brawling Prowess Lv 4": ["Grants Hit +8, Avo +16, and Crit Avo +8 when brawling.",    "Raise Brawling skill level to B+"],
    "Brawling Prowess Lv 5": ["Grants Hit +10, Avo +20, and Crit Avo +10 when brawling.",    "Raise Brawling skill level to A+"],
    "Canto": ["Allows unit to move again after completing certain actions, if there is movement remaining.",    "Class: Cavalier, Pegasus Knight, Wyvern Master, Paladin, Wyvern Lord, Barbarossa, Falcon Knight, Wyvern Lord, Great Knight, Bow Knight, Holy Knight, Dark Knight"],
    "Catnap": ["If unit takes no action except Wait, recovers up to 10% of max HP.",    "Personal: Linhardt"],
    "Cavalry Effect Null": ["Nullifies any extra effectiveness against cavalry units.",    "Raise Riding skill level to S+"],
    "Charm": ["Adjacent allies deal 3 extra damage during combat.",    "Class: Lord, Armored Lord, High Lord, Wyvern Master, Emperor, Great Lord, Barbarossa"],
    "Close Counter": ["Allows unit to counterattack adjacent foes.",    "Raise Bow skill level to C"],
    "Compassion": ["Use Rally to grant Lck +8 to an ally.", "Personal: Alois"],
    "Confidence": ["Grants Hit/Avo +15 when unit is at full HP.",    "Personal: Ferdinand"],
    "Crest Scholar": ["Use Rally to grant Mag +4 to an ally.",    "Personal: Hanneman"],
    "Crit +20": ["Increases Crit by 20.", "Class: War Master"],
    "Cursed Power": ["Unit recovers HP on swamp terrain.", ""],
    "Dance": ["Use Dance to allow an ally to move again.", "Class: Dancer"],
    "Dark Magic Avo +20": ["When using dark magic, Grants Avo +20 .", ""],
    "Dark Magic Crit +10": ["When using dark magic, Grants Crit +10 .", ""],
    "Dark Magic Range +1": ["Increases dark magic range by 1.",    "Raise Reason skill level to S for Edelgard, Hubert or Lysithea"],
    "Dark Magic Uses x2": ["Doubles the number of uses for dark magic.",    "Class: Gremory"],
    "Dark Magic Uses x4": ["Quadruples the number of uses for dark magic.", ""],
    "Dark Tomefaire": ["Grants Atk +5 when using dark magic.",    "Raise Reason skill level to S+ for Edelgard, Hubert or Lysithea, Class: Dark Knight"],
    "Darting Blow": ["If unit initiates combat, grants AS +6 during combat",    "Class mastered: Pegasus Knight"],
    "Death Blow": ["If unit initiates combat, grants Str +6 during combat.",    "Class mastered: Brigand"],
    "Defense +2": ["Increases Def by 2.", "Class mastered: Soldier"],
    "Defensive Tactics": ["Battalion endurance takes half damage.",    "Raise Authority skill level to B"],
    "Defiant Avo": ["Grants Avo +30 when HP is ≤ 25%.",    "Class mastered: Falcon Knight"],
    "Defiant Crit": ["Grants Crit +50 when HP is ≤ 25%.",    "Class mastered: Wyvern Lord"],
    "Defiant Def": ["Grants Def +8 when HP is ≤ 25%.",    "Class mastered: Great Knight"],
    "Defiant Mag": ["Grants Mag +8 when HP is ≤ 25%.",    "Class mastered: Gremory"],
    "Defiant Res": ["Grants Res +8 when HP is ≤ 25%.",    "Class mastered: Holy Knight"],
    "Defiant Spd": ["Grants Spd +8 when HP is ≤ 25%.",    "Class mastered: Bow Knight"],
    "Defiant Str": ["Grants Str +8 when HP is ≤ 25%.",    "Class mastered: Hero"],
    "Desperation": ["If unit initiates combat with HP ≤ 50%, unit's follow-up attack (if possible) occurs before foe's counterattack.",    "Class mastered: Cavalier"],
    "Dexterity +4": ["Increases Dex by 4.", "Raise Riding skill level to C"],
    "Discipline": ["Doubles skill experience earned in battle.", ""],
    "Distinguished House": ["Unit deals 2 extra damage while in formation with a battalion.",    "Personal: Lorenz"],
    "Divine Dragon Horn": ["Unit recovers 100% of HP at the start of each turn if a White Beast is within 10 spaces.",    ""],
    "Dragon Effect Null": ["Cancels effectiveness against dragons.", ""],
    "Effect Null": ["Cancels all types of effectiveness.", ""],
    "Faith Lv 1": ["Grants Hit +5, Avo +7, and Crit Avo +5 when using white magic.",    "Raise Faith skill level to E+"],
    "Faith Lv 2": ["Grants Hit +6, Avo +10, and Crit Avo +6 when using white magic.",    "Raise Faith skill level to D+"],
    "Faith Lv 3": ["Grants Hit +7, Avo +13, and Crit Avo +7 when using white magic.",    "Raise Faith skill level to C+"],
    "Faith Lv 4": ["Grants Hit +8, Avo +16, and Crit Avo +8 when using white magic.",    "Raise Faith skill level to B+"],
    "Faith Lv 5": ["Grants Hit +10, Avo +20, and Crit Avo +10 when using white magic.",    "Raise Faith skill level to A+"],
    "Fiendish Blow": ["If unit initiates combat, grants Mag +6 during combat",    "Class: Dark Bishop, Class mastered: Mage"],
    "Fighting Spirit": ["Unit takes 5 less damage when no battalion is assigned or when battalion endurance is 0.",    "Personal: Catherine"],
    "Fire": ["Allows unit to cast Fire. If Fire is already available, then unit can cast it twice as often.",    "Class: Mage"],
    "Fistbreaker": ["Grants Hit/Avo +20 when using a bow against brawlers.",    "Raise Bow skill level to B"],
    "Fistfaire": ["Grants Atk +5 when brawling.",    "Raise Brawling skill level to S+, Class: Grappler, War Master"],
    "Flying Effect Null": ["Nullifies any extra effectiveness against fliers.",    "Raise Flying skill level to S+"],
    "Goody Basket": ["Chance to recover up to 10% of max HP at the start of each turn. Trigger % = Lck stat.",    "Personal: Raphael"],
    "Guardian": ["Adjacent female allies deal 3 extra damage during combat.",    "Personal: Seteth"],
    "HP +5": ["Increases maximum HP by 5.", "Class mastered: Noble or Commoner"],
    "Heal": ["Allows unit to cast Heal. If Heal is already available, then unit can cast it twice as often.",    "Class: Priest"],
    "Heartseeker": ["Adjacent foes suffer Avo -20 during combat.",    "Class: Dark Mage, Dark Bishop"],
    "Hit +20": ["Increases Hit by 20.", "Class mastered:Archer"],
    "Hunter's Boon": ["Grants Crit +20 when foe's HP is ? 50%.",    "Personal: Petra"],
    "Immune Status": ["Nullifies status effects and debuffs.", ""],
    "Imperial Lineage": ["Multiplies experience earned by 1.2.",    "Personal: Edelgard"],
    "Imperial Lineage+": ["If unit takes no action except Wait, grants Res +4 for 1 turn. Multiplies experience earned by 1.2.",    "Personal: Edelgard (from Part 2)"],
    "Infantry Effect Null": ["Cancels effectiveness against infantry units.", ""],
    "Infinite Magic": ["Removes the limitation on the number of times magic can be used.",    ""],
    "Infirmary Master": ["Adjacent allies gain Crit Avo +10 during combat.",    "Personal: Manuela"],
    "Keen Intuition": ["Grants Avo +30 during combat with a foe 2 or more spaces away.",    ""],
    "Lady Knight": ["Grants Mt +3 and Hit +5 with gambits.", "Personal: Ingrid"],
    "Lance Avo +20": ["When using a lance, Grants Avo +20 .", ""],
    "Lance Crit +10": ["Grants Crit +10 when using a lance.",    "Raise Lance skill level to S"],
    "Lance Prowess Lv 1": ["Grants Hit +6, Avo +6, and Crit Avo +5 when using a lance.",    "Raise Lance skill level to E+"],
    "Lance Prowess Lv 2": ["Grants Hit +8, Avo +8, and Crit Avo +6 when using a lance.",    "Raise Lance skill level to D+"],
    "Lance Prowess Lv 3": ["Grants Hit +10, Avo +10, and Crit Avo +7 when using a lance.",    "Raise Lance skill level to C+"],
    "Lance Prowess Lv 4": ["Grants Hit +12, Avo +12, and Crit Avo +8 when using a lance.",    "Raise Lance skill level to B+"],
    "Lance Prowess Lv 5": ["Grants Hit +15, Avo +15, and Crit Avo +10 when using a lance.",    "Raise Lance skill level to A+"],
    "Lancebreaker": ["Grants Hit/Avo +20 when using an axe against lance users.",    "Raise Axe skill level to B"],
    "Lancebreaker+": ["Grants Hit/Avo +30 when using an axe against lance users.",    ""],
    "Lancefaire": ["Grants Atk +5 when using a lance.",    "Raise Lance skill level to S+, Class: High Lord, Paladin, Great Lord, Falcon Knight, Great Knight"],
    "Leicester Lineage": ["Multiplies experience earned by 1.2.",    "Personal: Claude"],
    "Leicester Lineage+": ["Allows unit to pass through spaces occupied by foes. Multiplies experience earned by 1.2.",    "Personal: Claude (from Part 2)"],
    "Lethality": ["Chance to instantly kill a foe when dealing damage. Trigger % = 0.25\xc3\x97Dex.",    "Class mastered: Assassin"],
    "Lifetaker": ["Unit recovers HP equal to 50% of damage dealt after defeating a foe.",    "Class mastered: Dark Bishop"],
    "Lily's Poise": ["Adjacent allies take 3 less damage during combat.",    "Personal: Flayn"],
    "Live to Serve": ["When healing an ally with white magic, unit recovers the same amount of HP.",    "Personal: Mercedes"],
    "Lockpick": ["Allows unit to open doors and chests without keys.",    "Personal: Ashe"],
    "Locktouch": ["Allows unit to open doors and chests without keys.",    "Class: Thief, Assassin"],
    "Lone Wolf": ["Unit deals 5 extra damage when no battalion is assigned or when battalion endurance is 0.",    "Personal: Felix"],
    "Magic +2": ["Increases Mag by 2.", "Class mastered: Monk"],
    "Magic Bind": ["If unit lands a hit, targeted foe is unable to use magic for 1 turn.",    ""],
    "Mastermind": ["Doubles skill experience earned in battle.",    "Personal: Lysithea"],
    "Miasma Δ": ["Allows unit to cast Miasma Δ. If Miasma Δ is already available, then unit can cast it twice as often.",    "Class: Dark Mage, Dark Bishop"],
    "Miracle": ["Chance to survive lethal damage with 1 HP, if HP is > 1. Trigger % = Lck stat.",    "Class mastered: Priest"],
    "Missing Number": ["Missing Number (icon is based on Wary Fighter)",    "SpoOoOoky"],
    "Model Leader": ["Doubles experience earned for battalions.",    "Raise Authority skill level to C+ for protagonist, Edelgard, Dimitri, Claude or Seteth"],
    "Movement +1": ["Increases Mv by 1.", "Raise Riding skill level to A+"],
    "Murderous Intent": ["If unit initiates combat, grants Hit +20 during combat.",    ""],
    "Noncombatant": ["Unit cannot be targeted by foes.", ""],
    "Offensive Tactics": ["Grants Mt +5 and Hit +20 with gambits.",    "Raise Authority skill level to S+"],
    "Officer Duty": ["Grants Mt +5 with gambits.", "Personal: Hubert"],
    "Paragon": ["Doubles experience earned.", ""],
    "Pass": ["Allows unit to pass through spaces occupied by foes.",    "Budding talent: Bernadetta"],
    "Path of the Conqueror": ["On Hold", "Unused?"],
    "Pavise": ["Chance to reduce sword/lance/axe/brawling damage by half. Trigger % = Dex stat.",    "Class mastered: Fortress Knight"],
    "Persecution Complex": ["Grants Atk +5 when unit is not at full HP.",    "Personal: Bernadetta"],
    "Perseverance": ["Use Rally to grant Str +4 to an ally.",    "Personal: Annette"],
    "Philanderer": ["If a female ally is adjacent, unit deals 2 extra damage and takes 2 less damage during combat.",    "Personal: Sylvain"],
    "Poison Strike": ["If unit initiates combat and lands a hit, targeted foe loses up to 20% of max HP after combat.",    "Class mastered: Dark Mage"],
    "Pomp & Circumstance": ["Grants Lck/Cha +4.",    "Class mastered: Armored Lord, High Lord or Wyvern Master"],
    "Professor’s Guidance": ["Multiplies this unit's and adjacent allies' experience earned by 1.2.",    "Personal: Protagonist"],
    "Professor's Guidance+": ["Unit deals 2 extra damage during combat. Multiplies this unit's and adjacent allies' experience earned by 1.2.",    "Personal: Protagonist (halfway through Chapter 10's story mission)"],
    "Quick Riposte": ["If foe initiates combat while unit's HP is \xe2\x89\xa5 50%, unit makes guaranteed follow-up attack.",    "Class mastered: War Master"],
    "Rally Charm": ["Use Rally to grant Cha +8 to an ally.",    "Raise Authority skill level for Edelgard (S), Dorothea (D), Dimitri (S), Claude (S) or Manuela (D)"],
    "Rally Defense": ["Use Rally to grant Def +4 to an ally.",    "Raise Authority skill level to D for Seteth or Gilbert"],
    "Rally Dexterity": ["Use Rally to grant Dex +8 to an ally.",    "Raise Authority skill level for Ferdinand (D) or Ignatz (C+)"],
    "Rally Luck": ["Use Rally to grant Lck +8 to an ally.",    "Raise Authority skill level to D for Flayn"],
    "Rally Magic": ["Use Rally to grant Mag +4 to an ally.",    "Raise Authority skill level to D for Hubert or Ingrid"],
    "Rally Movement": ["Use Rally to grant Mv +1 to an ally.",    "Raise Authority skill level to S for protagonist or Annette"],
    "Rally Resistance": ["Use Rally to grant Res +4 to an ally.",    "Raise Authority skill level for Hubert (C+), Annette (D) or Seteth (S)"],
    "Rally Speed": ["Use Rally to grant Spd +4 to an ally.",    "Raise Authority skill level for Hubert (S), Annette (C+) or Ignatz (D)"],
    "Rally Strength": ["Use Rally to grant Str +4 to an ally.",    "Raise Authority skill level for Raphael (C), Ignatz (S) or Alois (D)"],
    "Reason Lv 1": ["Grants Hit +7, Avo +5, and Crit Avo +5 when using black or dark magic.",    "Raise Reason skill level to E+"],
    "Reason Lv 2": ["Grants Hit +10, Avo +6, and Crit Avo +6 when using black or dark magic.",    "Raise Reason skill level to D+"],
    "Reason Lv 3": ["Grants Hit +13, Avo +7, and Crit Avo +7 when using black or dark magic.",    "Raise Reason skill level to C+"],
    "Reason Lv 4": ["Grants Hit +16, Avo +8, and Crit Avo +8 when using black or dark magic.",    "Raise Reason skill level to B+"],
    "Reason Lv 5": ["Grants Hit +20, Avo +10, and Crit Avo +10 when using black or dark magic.",    "Raise Reason skill level to A+"],
    "Renewal": ["Unit recovers up to 20% of max HP at the start of each turn.",    "Class mastered: Bishop"],
    "Resistance +2": ["Increases Res by 2.", "Class mastered: Lord"],
    "Rivalry": ["If a male ally is adjacent, unit deals 2 extra damage and takes 2 less damage during combat.",    "Personal: Leonie"],
    "Royal Lineage": ["Multiplies experience earned by 1.2.",    "Personal: Dimitri"],
    "Royal Lineage+": ["Grants Avo +20 while unit is at full HP. Multiplies experience earned by 1.2.",    "Personal: Dimitri (from Part 2)"],
    "Sacred Power": ["Adjacent allies deal 3 extra damage and take 3 less damage during combat.",    "Personal: Rhea, Class mastered: Enlightened One"],
    "Seal Defense": ["If unit damages foe during combat, foe suffers Def -6 for 1 turn after combat.",    "Class mastered: Wyvern Rider"],
    "Seal Magic": ["If unit damages foe during combat, foe suffers Mag -6 for 1 turn after combat.",    "Budding talent: Flayn"],
    "Seal Movement": ["If unit damages foe during combat, foe suffers Mv -1 for 1 turn after combat.",    "Budding talent: Dimitri"],
    "Seal Resistance": ["If unit damages foe during combat, foe suffers Res -6 for 1 turn after combat.",    "Class mastered: Dark Knight"],
    "Seal Speed": ["If unit damages foe during combat, foe suffers Spd -6 for 1 turn after combat.",    "Budding talent: Ferdinand"],
    "Seal Strength": ["If unit damages foe during combat, foe suffers Str -6 for 1 turn after combat.",    "Budding talent: Ignatz"],
    "Songstress": ["Adjacent allies recover up to 10% of max HP at the start of each turn.",    "Personal: Dorothea"],
    "Special Dance": ["When using the Dance ability, grant Dex/Spd/Lck +4 to target ally.",    "Class mastered: Dancer"],
    "Speed +2": ["Increases Spd by 2.", "Class mastered: Myrmidon"],
    "Staunch Shield": ["If unit takes no action except Wait, grants Def +4 for 1 turn.",    "Personal: Dedue"],
    "Steal": ["Allows unit to steal a non-weapon item from a foe with a lower Spd stat.",    "Class: Thief, Class mastered: Thief"],
    "Stealth": ["Makes it more difficult for foes to target unit.",    "Class: Assassin"],
    "Strength +2": ["Increases Str by 2.", "Class mastered: Fighter"],
    "Survival Instinct": ["If unit initiates combat and defeats foe, grants Str/Mag/Dex/Spd +4 for one turn.",    "Personal: Shamir"],
    "Sword Avo +20": ["Grants Avo +20 when using a sword.", ""],
    "Sword Crit +10": ["Grants Crit +10 when using a sword.",    "Raise Sword skill level to S, Class: Swordmaster"],
    "Sword Prowess Lv 1": ["Grants Hit +5, Avo +7, and Crit Avo +5 when using a sword.",    "Raise Sword skill level to E+"],
    "Sword Prowess Lv 2": ["Grants Hit +6, Avo +10, and Crit Avo +6 when using a sword.",    "Raise Sword skill level to D+"],
    "Sword Prowess Lv 3": ["Grants Hit +7, Avo +13, and Crit Avo +7 when using a sword.",    "Raise Sword skill level to C+"],
    "Sword Prowess Lv 4": ["Grants Hit +8, Avo +16, and Crit Avo +8 when using a sword.",    "Raise Sword skill level to B+"],
    "Sword Prowess Lv 5": ["Grants Hit +10, Avo +20, and Crit Avo +10 when using a sword.",    "Raise Sword skill level to A+"],
    "Swordbreaker": ["Grants Hit/Avo +20 when using a lance against sword users.",    "Raise Lance skill level to B"],
    "Swordbreaker+": ["Grants Hit/Avo +30 when using a lance against sword users.",    ""],
    "Swordfaire": ["Grants Atk +5 when using a sword.",    "Raise Sword skill level to S+, Class: Hero, Swordmaster, Assassin, Enlightened One, Mortal Savant"],
    "Terrain Resistance": ["Nullifies damage from terrain.",    "Class: Paladin, Bishop, Enlightened One, Holy Knight"],
    "Tomebreaker": ["Grants Hit/Avo +20 when brawling against magic users.",    "Raise Brawling skill level to B"],
    "Unarmed Combat": ["Allows unit to fight without a weapon.",    "Class: Brawler, Grappler, Class mastered: Brawler"],
    "Unsealable Magic": ["Prevents unit from being silenced.", ""],
    "Vantage": ["When foe initiates combat, unit still attacks first if HP is ≤ 50%.",    "Class mastered: Mercenary, Class: Hero"],
    "Veteran Knight": ["Unit takes 2 less damage while in formation with a battalion.",    "Personal: Gilbert"],
    "Warding Blow": ["If unit initiates combat, grants Res +6 during combat",    "Class mastered: Mortal Savant"],
    "Watchful Eye": ["Grants Hit +20.", "Personal: Ignatz"],
    "Weight -3": ["Reduces total equipment weight by 3.",    "Raise Heavy Armour skill level to C"],
    "Weight -5": ["Reduces total equipment weight by 5.",    "Raise Heavy Armour skill level to A+, Class: Fortress Knight"],
    "White Magic Avo +20": ["Grants Avo +20 when using white magic.",    "Budding talent: Dorothea"],
    "White Magic Crit +10": ["When using white magic, Grants Crit +10 .", ""],
    "White Magic Heal +10": ["Heal 10 extra HP when using white magic.",    "Class: Bishop"],
    "White Magic Heal +5": ["Heal 5 extra HP when using white magic.",    "Class: Priest"],
    "White Magic Range +1": ["Increases white magic range by 1 for attacks that damage foes.",    "Raise Faith skill level to S"],
    "White Magic Uses Up+": ["Quadruples the number of uses for white magic.",    ""],
    "White Magic Uses x2": ["Doubles the number of uses for white magic.",    "Class: Bishop, Gremory"],
    "White Tomefaire": ["Grants Atk +5 when using white magic.",    "Raise Faith skill level to S+, Class: Holy Knight"],
    "Wrath": ["If foe initiates combat while unit's HP is ≤ 50%, grants Crit +50.",    "Class mastered: Warrior"]
  };

// also only learnable ones
var universal_abilities = [
    "Sword Prowess Lv 1",
    "Sword Prowess Lv 2",
    "Sword Prowess Lv 3",
    "Axebreaker",
    "Sword Prowess Lv 4",
    "Sword Prowess Lv 5",
    "Sword Crit +10",
    "Swordfaire",
    "Lance Prowess Lv 1",
    "Lance Prowess Lv 2",
    "Lance Prowess Lv 3",
    "Swordbreaker",
    "Lance Prowess Lv 4",
    "Lance Prowess Lv 5",
    "Lance Crit +10",
    "Lancefaire",
    "Axe Prowess Lv 1",
    "Axe Prowess Lv 2",
    "Axe Prowess Lv 3",
    "Lancebreaker",
    "Axe Prowess Lv 4",
    "Axe Prowess Lv 5",
    "Axe Crit +10",
    "Axefaire",
    "Bow Prowess Lv 1",
    "Bow Prowess Lv 2",
    "Close Counter",
    "Bow Prowess Lv 3",
    "Bow Prowess Lv 4",
    "Bow Prowess Lv 5",
    "Bow Crit +10",
    "Bowfaire",
    "Brawling Prowess Lv 1",
    "Brawling Prowess Lv 2",
    "Brawling Prowess Lv 3",
    "Brawling Prowess Lv 4",
    "Brawling Prowess Lv 5",
    "Brawl Crit +10",
    "Fistfaire",
    "Reason Lv 1",
    "Reason Lv 2",
    "Reason Lv 3",
    "Reason Lv 4",
    "Reason Lv 5",
    "Black Magic Range +1",
    "Black Tomefaire",
    "Faith Lv 1",
    "Faith Lv 2",
    "Faith Lv 3",
    "Faith Lv 4",
    "Faith Lv 5",
    "White Magic Range +1",
    "White Tomefaire",
    "Authority Lv 1",
    "Authority Lv 2",
    "Authority Lv 3",
    "Defensive Tactics",
    "Authority Lv 4",
    "Authority Lv 5",
    "Offensive Tactics",
    "Weight -3",
    "Weight -5",
    "Armored Effect Null",
    "Dexterity +4",
    "Movement +1",
    "Cavalry Effect Null",
    "Alert Stance",
    "Alert Stance+",
    "Flying Effect Null",
    "Aegis",
    "Armored Blow",
    "Darting Blow",
    "Death Blow",
    "Defense +2",
    "Defiant Avo",
    "Defiant Crit",
    "Defiant Def",
    "Defiant Mag",
    "Defiant Res",
    "Defiant Spd",
    "Defiant Str",
    "Desperation",
    "Fiendish Blow",
    "HP +5",
    "Hit +20",
    "Lethality",
    "Lifetaker",
    "Magic +2",
    "Miracle",
    "Pavise",
    "Poison Strike",
    "Pomp & Circumstance",
    "Quick Riposte",
    "Renewal",
    "Resistance +2",
    "Sacred Power",
    "Seal Defense",
    "Seal Resistance",
    "Special Dance",
    "Speed +2",
    "Strength +2",
    "Unarmed Combat",
    "Vantage",
    "Warding Blow",
    "Wrath",
]

export {spells, combat_arts, universal_arts , allabilities, universal_abilities};
